name: Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  scrape-and-save:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      UPLOAD_API_KEY: ${{ secrets.UPLOAD_API_KEY }}
      UPLOAD_API_URL: ${{ secrets.UPLOAD_API_URL }}
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium
        run: playwright install chromium

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git pull origin main
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add schedules.json
          git add invalid_schedules.json
          git add schedules_html_table_cache.json
          git commit -m "Update schedules and caches ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))" || echo "No changes to commit"
          git push origin main
